require 'patches/class'
require 'patches/file'
require 'patches/hash'
require 'patches/numeric'
require 'patches/enumerable'

require 'pipeline/auditing'
require 'pipeline/cleaning'
require 'pipeline/base'
require 'pipeline/config'
require 'pipeline/usage'
require 'pipeline/config_generator'
require 'pipeline/logger'
#require 'pipeline/sample_config'
require 'pipeline/sample_object'
require 'pipeline/scheduling'
require 'pipeline/script'
require 'pipeline/step'
require 'pipeline/tools'
require 'pipeline/task'
require 'pipeline/timer'

require 'colored'
require 'extlib'
require 'json'
require 'nokogiri'
