:pindel:
  :normal:
    :max_alt_count: 0
    :min_depth: 8
  :tumor:
    :min_alt_count: 2
    :min_depth: 14
    :max_alt_length: 15
    :max_ref_length: 15
:mutect:
  :has_judgement: KEEP
  :include_dbsnp_site: [ COSMIC, NOVEL ]
  :has_covered: COVERED
:oncotator:
  :exclude_txp_variant_classification: [ "5\'Flank", "3\'Flank", "5\'UTR", "3\'UTR", Intron, RNA ]
  #:is_snp: false
:univ_geno_normal:
  :vcf:
    :min_alt_freq: 0.25
    :min_depth: 14
  :oncotator:
    :exclude_txp_variant_classification: [ IGR, Intron, UTR, Flank, RNA ]
    :is_cancerous: true
