:pindel:
  :normal:
    :max_alt_count: 0
    :min_depth: 8
  :tumor:
    :min_alt_count: 2
    :min_depth: 14
:mutect:
  :has_judgement: KEEP
  :include_dbsnp_site: [ COSMIC, NOVEL ]
  :has_covered: COVERED
:oncotator:
  :exclude_txp_variant_classification: [ Silent, IGR, Intron, UTR, Flank, RNA ]
  #:is_snp: false
