:pindel:
  :normal:
    :max_alt_count: 0
    :min_depth: 8
  :tumor:
    :min_alt_count: 2
    :min_depth: 14
    :max_alt_length: 50
    :max_ref_length: 50
    :min_alt_freq: 0.03
:mutect:
  :germline:
    :has_judgement: REJECT
    :has_covered: COVERED
    :min_n_var_freq: 0.1
    :min_t_var_freq: 0.1
  :somatic:
    :either:
      :all1:
        :include_dbsnp_site: COSMIC
        :max_n_alt_count: 1
        :min_t_alt_count: 3
      :all2:
        :has_judgement: KEEP
        :has_covered: COVERED
    :max_q0_ratio: 1
    #:whitelisted: whitelist.gtf
  #:include_dbsnp_site: [ COSMIC, NOVEL ]
:somaticindel:
  :normal:
    :max_alt_count: 0
    :min_depth: 8
  :tumor:
    :min_alt_count: 4
    :min_depth: 14
    :max_alt_mismatch_rate: 0.2
    :max_alt_mismatch_count: 3
    :min_alt_base_quality: 10
    :min_alt_map_quality: 20
    #:max_alt_length: 50
    #:max_ref_length: 50
    :min_alt_freq: 0.05
:snpeff:
  :exclude_annotation:  [ intergenic_region, downstream_gene_variant, non_coding_exon_variant, upstream_gene_variant, intron_variant, TF_binding_site_variant, 3_prime_UTR_variant, intragenic_variant, 5_prime_UTR_variant ]
  :has_gene_id: true
  #:is_snp: false
:oncotator:
  :exclude_txp_variant_classification: [ IGR, Intron, UTR, Flank, RNA ]
  :has_txp_gene: true
  #:is_snp: false
:univ_geno_normal:
  :vcf:
    :min_alt_freq: 0.25
    :min_depth: 14
  :oncotator:
    :exclude_txp_variant_classification: [ IGR, Intron, UTR, Flank, RNA ]
    :is_cancerous: true
