:pindel:
  :normal:
    :max_alt_count: 0
    :min_depth: 8
  :tumor:
    :min_alt_count: 2
    :min_depth: 14
    :max_alt_length: 50
    :max_ref_length: 50
    :min_alt_freq: 0.03
:mutect:
  :either:
    :has_judgement: KEEP
    :has_dbsnp_site: COSMIC
    #:whitelisted: whitelist.gtf
  #:include_dbsnp_site: [ COSMIC, NOVEL ]
  :has_covered: COVERED
:oncotator:
  :exclude_txp_variant_classification: [ Silent, IGR, Intron, UTR, Flank, RNA ]
  #:is_snp: false
:univ_geno_normal:
  :vcf:
    :min_alt_freq: 0.25
    :min_depth: 14
  :oncotator:
    :exclude_txp_variant_classification: [ Silent, IGR, Intron, UTR, Flank, RNA ]
    :is_cancerous: true
