:pindel:
  :normal:
    :max_alt_count: 0
    :min_depth: 8
  :tumor:
    :min_alt_count: 4
    :min_depth: 14
    :max_alt_length: 50
    :max_ref_length: 50
    :min_alt_freq: 0.1
:indelocator:
  :normal:
    :max_alt_count: 0
    :min_depth: 8
  :tumor:
    :min_alt_count: 4
    :min_depth: 14
    :max_alt_length: 50
    :max_ref_length: 50
    :min_alt_freq: 0.1
:somaticindel:
  :normal:
    :max_alt_count: 0
    :min_depth: 8
  :tumor:
    :min_alt_count: 4
    :min_depth: 14
    :max_alt_mismatch_rate: 0.2
    :max_alt_mismatch_count: 3
    :min_alt_base_quality: 10
    :min_alt_map_quality: 20
    :max_alt_length: 50
    :max_ref_length: 50
    :min_alt_freq: 0.05
:mutect:
  :germline:
    :has_dbsnp_site: COSMIC
    :has_covered: COVERED
    :min_n_var_freq: 0.1
    :min_t_var_freq: 0.1
  :somatic:
    :has_judgement: KEEP
    :has_covered: COVERED
    :max_q0_ratio: 1
#  :has_judgement: KEEP
#  :include_dbsnp_site: [ COSMIC, NOVEL ]
#  :has_covered: COVERED
:oncotator:
  :exclude_txp_variant_classification: []
  #:is_snp: false
:univ_geno_normal:
  :vcf:
    :min_alt_freq: 0.25
    :min_depth: 14
  :oncotator:
    :exclude_txp_variant_classification: [ ]
    :is_cancerous: true
