# The BWA index
:bwa_idx: /cbc/resources/human/hg19/bwa_index/bwa-latest/hg19.fa

# The Bowtie index
:bowtie_idx: /cbc/resources/human/hg19/bowtie_index/hg19
:bowtie2_idx: /cbc/resources/human/hg19/bowtie2_index/hg19

:chimerascan_idx: /cbc/resources/human/hg19/chimerascan_index
# Some resource files
:transcriptome_idx: /cbc/resources/human/hg19/gencode/gencode.v11.tophat2
:hg19_dict: /cbc/resources/human/hg19/ucsc_feb_2009/hg19.dict
:hg19_fa: /cbc/resources/human/hg19/ucsc_feb_2009/hg19.fa
:hg19_2bit: /cbc/resources/human/hg19/ucsc_feb_2009/hg19.2bit
:hg19_date: feb_2009
:hg19_reference_gtf: /cbc/resources/human/hg19/refSeq/refFlat.hg19.gtf
:hg19_ucsc_gtf: /cbc/resources/human/hg19/ucsc_feb_2009/knownGene.trimmed.gtf
:hg19_ucsc_gene_names: /cbc/resources/human/hg19/ucsc_feb_2009/kgXref.txt
:hg19_gencode_gtf: /cbc/resources/human/hg19/gencode/gencode.v11.annotation.gtf
:hg19_unified_gtf: /cbc/resources/human/hg19/gencode/gencode.v11.annotation.highQ.ccds.unified_model.gtf
:hg19_features_gtf: /cbc/resources/human/hg19/gencode/gencode.v11.annotation.highQ.ccds.features.gtf
:hg19_refflat_gtf: /cbc/resources/human/hg19/refSeq/refFlat.hg19.gtf
:hg19_null_gtf: /cbc/resources/human/hg19/null_candidate_genomic_regions.gtf
:hg19_refflat: /cbc/resources/human/hg19/refSeq/refFlat.hg19.20111003.txt
:hg19_rsem: /cbc/resources/human/hg19/rsem/gencode/rsem_gencode.v18_hg19

:hg19_indel_vcf: /cbc/resources/human/hg19/1000G/1000G_biallelic.indels.hg19.sorted.vcf
:hg19_snp_vcf: /cbc/resources/human/hg19/dbSNP/dbsnp_132.hg19.sorted.vcf

:thousand_genomes_indels: /cbc/resources/human/hg19/1000G/1000G_biallelic.indels.hg19.sorted.vcf
:dbsnp_vcf: /cbc/resources/human/hg19/dbSNP/dbsnp_132.hg19.sorted.vcf
:cosmic_vcf: /cbc/resources/human/hg19/cosmic/CosmicMutantExport_v56_151111.vcf

:hg19_rrna_intervals: /cbc/resources/human/hg19/intervals/rrna/Homo_sapiens_assembly19.rRNA,1-25,BST20120223.interval_list
:agilent_intervals: /cbc/resources/human/hg19/intervals/agilent/029720_D_BED_20101013_agilent_50mb_exon_hg19.interval_list
:hg19_interval_bed: /cbc/resources/human/hg19/intervals/whole_genome/hg19.50kb.bed
:hg19_gc: /cbc/resources/human/hg19/misc/hg19.50kb.gc.txt
