:bwa_idx: /cbc/resources/human/hg38/bwa_index/Homo_sapiens.GRCh38.dna.wholechrom.fa
:kallisto_index: /cbc/resources/human/hg38/ensembl/Homo_sapiens_GRCch38.idx
:hg38_rsem: /cbc/resources/human/hg38/Homo_sapiens.GRCh38.85
:hg38_refflat: /cbc/resources/human/hg38/refFlat.hg38.85.20161209.txt
:hg38_rrna_intervals: /cbc/resources/human/hg38/Homo_sapiens.GRCh38.85.rRNA.20160902.interval_list
:hg38_rrna_bwa_intervals: /cbc/resources/human/hg38/Homo_sapiens.GRCh38.85.rRNA.20160921.interval_bwa_list
:hg38_reference_gtf: /cbc/resources/human/hg38/Homo_sapiens.GRCh38.85.gtf
:hgnc_complete: /cbc/resources/human/hg38/hgnc_complete_set.txt
:ensembl_pc_genes: /cbc/resources/human/hg38/ensembl_pc_genes.txt
:rrna_bwa_idx: /cbc/resources/human/hg38/human.rrna.fa
:mt_rna_contigs: MT-RNR1 MT-RNR2
