#Align paired end sequence for a set of conditions, with normal and tumor samples

:pipe: ribo
:script: prof_align
:output_dir: ./output
:metrics_dir: ./metrics
:scratch_dir: ./scratch
:log_dir: ./log
:adapter: CTGTAGGCACCATCAAT
:qual_type: phred64

#:keep_temp_files: true
#:verbose: true
