#Align paired end sequence for a set of conditions, with normal and tumor samples

:script: paired_align
:job_name: rnaseq_oct_2012
:samples: 
  - :sample_name: HCC364
    :replicates:
      - :input_fastq1_list: 
          - /home/sasthana/data/RNAseq_Oct_2012/Project_Bivona/Sample_LL2_index13/LL2_index13_AGTCAA_L002_R1_001.fastq.gz
        :input_fastq2_list:
          - /home/sasthana/data/RNAseq_Oct_2012/Project_Bivona/Sample_LL2_index13/LL2_index13_AGTCAA_L002_R2_001.fastq.gz
  - :sample_name: HCC364_4032_R1
    :replicates:
      - :input_fastq1_list:
          - /home/sasthana/data/RNAseq_Oct_2012/Project_Bivona/Sample_LL2_index15/LL2_index15_ATGTCA_L002_R1_001.fastq.gz
        :input_fastq2_list:
          - /home/sasthana/data/RNAseq_Oct_2012/Project_Bivona/Sample_LL2_index15/LL2_index15_ATGTCA_L002_R2_001.fastq.gz
  - :sample_name: HCC364_4032_R2
    :replicates:
      - :input_fastq1_list:
          - /home/sasthana/data/RNAseq_Oct_2012/Project_Bivona/Sample_LL3_index16/LL3_index16_CCGTCC_L003_R1_001.fastq.gz
        :input_fastq2_list:
          - /home/sasthana/data/RNAseq_Oct_2012/Project_Bivona/Sample_LL3_index16/LL3_index16_CCGTCC_L003_R2_001.fastq.gz
  - :sample_name: HCC364_4032_R3
    :replicates:
      - :input_fastq1_list:
          - /home/sasthana/data/RNAseq_Oct_2012/Project_Bivona/Sample_LL3_index18/LL3_index18_GTCCGC_L003_R1_001.fastq.gz
        :input_fastq2_list:
          - /home/sasthana/data/RNAseq_Oct_2012/Project_Bivona/Sample_LL3_index18/LL3_index18_GTCCGC_L003_R2_001.fastq.gz
  - :sample_name: HCC364_4032_R4
    :replicates:
      - :input_fastq1_list:
          - /home/sasthana/data/RNAseq_Oct_2012/Project_Bivona/Sample_LL3_index19/LL3_index19_GTGAAA_L003_R1_001.fastq.gz
        :input_fastq2_list:
          - /home/sasthana/data/RNAseq_Oct_2012/Project_Bivona/Sample_LL3_index19/LL3_index19_GTGAAA_L003_R2_001.fastq.gz
  - :sample_name: HCC364_4720_R1
    :replicates:
      - :input_fastq1_list:
          - /home/sasthana/data/RNAseq_Oct_2012/correct_lane_4/Project_Bivona/Sample_LL5_index4/LL5_index4_TGACCA_L004_R1_001.fastq.gz
        :input_fastq2_list:
          - /home/sasthana/data/RNAseq_Oct_2012/correct_lane_4/Project_Bivona/Sample_LL5_index4/LL5_index4_TGACCA_L004_R2_001.fastq.gz
  - :sample_name: HCC364_PB3_R1
    :replicates:
      - :input_fastq1_list:
          - /home/sasthana/data/RNAseq_Oct_2012/correct_lane_4/Project_Bivona/Sample_LL4_index5/LL4_index5_ACAGTG_L004_R1_001.fastq.gz
        :input_fastq2_list:
          - /home/sasthana/data/RNAseq_Oct_2012/correct_lane_4/Project_Bivona/Sample_LL4_index5/LL4_index5_ACAGTG_L004_R2_001.fastq.gz
  - :sample_name: HCC364_PB3_R2
    :replicates:
      - :input_fastq1_list:
          - /home/sasthana/data/RNAseq_Oct_2012/correct_lane_4/Project_Bivona/Sample_LL4_index6/LL4_index6_GCCAAT_L004_R1_001.fastq.gz
        :input_fastq2_list:
          - /home/sasthana/data/RNAseq_Oct_2012/correct_lane_4/Project_Bivona/Sample_LL4_index6/LL4_index6_GCCAAT_L004_R2_001.fastq.gz
  - :sample_name: HCC364_PLX4032
    :replicates:
      - :input_fastq1_list:
          - /home/sasthana/data/RNAseq_Oct_2012/Project_Bivona/Sample_LL2_index14/LL2_index14_AGTTCC_L002_R1_001.fastq.gz
        :input_fastq2_list:
          - /home/sasthana/data/RNAseq_Oct_2012/Project_Bivona/Sample_LL2_index14/LL2_index14_AGTTCC_L002_R2_001.fastq.gz

:output_dir: ./output
:metrics_dir: ./metrics
:scratch_dir: ./scratch
:log_dir: ./log
:frag_size: 100

:filter_config: ./mutationConfig.cfg
:interval_list: /taylorlab/resources/human/hg19/intervals/agilent/029720_D_BED_20101013_agilent_50mb_exon_hg19.interval_list

:keep_temp_files: true
:verbose: true
