#Align paired end sequence for a set of conditions, with normal and tumor samples

:pipe: rna
:script: paired_align

:output_dir: ./output
:metrics_dir: ./metrics
:scratch_dir: ./scratch
:log_dir: ./log
:frag_size: 100

:keep_temp_files: true
:verbose: true

#:find_novel_transcripts: true # do transcript discovery without comparing to a reference GTF
